# Generated by Django 3.2.12 on 2022-03-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=30)),
                ('qr_code', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('bagage_service', models.BooleanField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('telephone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='router_specifications')),
            ],
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField(default='0.0')),
                ('longitude', models.FloatField(default='0.0')),
                ('distance', models.FloatField(default='-1')),
                ('deviation', models.FloatField(default='-1')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.participation')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.person'),
        ),
        migrations.AddField(
            model_name='participation',
            name='t_shirt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hagelandse101.tshirt'),
        ),
    ]
