# Generated by Django 3.2.12 on 2022-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hagelandse101', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.FileField(upload_to='route')),
            ],
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
