# Generated by Django 3.2.12 on 2022-04-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hagelandse101', '0002_auto_20220331_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nummer', models.IntegerField(null=True)),
                ('Serial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Badge_toekenning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Controlepunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nummer', models.IntegerField()),
                ('checkpointNaam', models.CharField(max_length=100)),
                ('Verantwoordelijke', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Deelname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Deelnemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voornaam', models.CharField(max_length=30)),
                ('Familienaam', models.CharField(max_length=30)),
                ('Roepnaam', models.CharField(max_length=30)),
                ('Stad', models.CharField(max_length=30)),
                ('Postcode', models.CharField(max_length=30)),
                ('Land', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.CharField(max_length=30)),
                ('Jaar', models.IntegerField()),
                ('Naam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tijd', models.DateField()),
                ('Controlepunt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.controlepunt')),
                ('Deelname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.deelname')),
            ],
        ),
        migrations.RemoveField(
            model_name='participation',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='t_shirt',
        ),
        migrations.RemoveField(
            model_name='position',
            name='participation',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='deelname',
            name='Deelnemer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.deelnemer'),
        ),
        migrations.AddField(
            model_name='deelname',
            name='Editie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.editie'),
        ),
        migrations.AddField(
            model_name='controlepunt',
            name='Editie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.editie'),
        ),
        migrations.AddField(
            model_name='badge_toekenning',
            name='Deelname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.deelname'),
        ),
        migrations.AddField(
            model_name='badge',
            name='Editie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hagelandse101.editie'),
        ),
    ]
